apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderplacer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: orderplacer
  template:
    metadata:
      labels:
        app: orderplacer
    spec:
      containers:
        - name: orderplacer
          image: 055540832687.dkr.ecr.ap-southeast-2.amazonaws.com/2tbot-order-placer:latest
          env:
            - name: spring.kafka.bootstrap-servers
              value: "kafka:9092"