apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: 055540832687.dkr.ecr.ap-southeast-2.amazonaws.com/2tbot-publisher:latest
          env:
            - name: spring.kafka.bootstrap-servers
              value: "kafka:9092"
            - name: app.runMexc
              value: "true"
            - name: app.runBybit
              value: "false"
