wss.bybit.url=wss://stream.bybit.com/contract/usdt/public/v3
wss.bybit.initMessageTemplate={"op": "subscribe","args": [%params]}
wss.bybit.pingMessage={"op": "ping", "args": []}
wss.bybit.pingInterval=15
wss.mexc.url=wss://contract.mexc.com/edge
wss.mexc.initMessageTemplate={"method":"sub.kline","param":{"symbol":"%symbol","interval":"Min%interval"}}
wss.mexc.pingMessage={"method": "ping"}
wss.mexc.pingInterval=15
kafka.mexc.output.topic=kline
kafka.mexc.output.error=mexc-error
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.tbot.cyclop.Cyclop.kafka.serializer.KlineDataSerializer
server.port=8081
spring.data.mongodb.uri=mongodb://root:root@ec2-47-129-30-225.ap-southeast-1.compute.amazonaws.com/?directConnection=true&tls=false
spring.data.mongodb.database=2tbot-be
app.runMexc=false
app.runBybit=false
app.compressRatio.1=3
app.compressRatio.5=30
app.compressRatio.15=30
app.compressRatio.30=50
app.compressRatio.60=70

