wss.bybit.url=wss://stream.bybit.com/contract/usdt/public/v3
wss.bybit.initMessage={"op": "subscribe","args": [%s]}
wss.bybit.pingMessage={"op": "ping", "args": []}
wss.mexc.url=wss://contract.mexc.com/edge
wss.mexc.initMessage={"method":"sub.tickers","param":{}}
wss.mexc.pingMessage={"method": "ping"}
kafka.mexc.output.topic=market-data
kafka.mexc.output.error=mexc-error
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.tbot.cyclop.Cyclop.kafka.serializer.MarketDataSerializer
