wss.bybit.url=wss://stream.bybit.com/contract/usdt/public/v3
wss.bybit.initMessage={"op": "subscribe","args": ["kline.1.BTCUSDT","kline.1.BTCUSDT","kline.1.BTCUSDT","kline.1.BTCUSDT","kline.1.BTCUSDT"]}
wss.bybit.pingMessage={"op": "ping", "args": []}
wss.bybit.pingInterval=15
wss.mexc.url=wss://contract.mexc.com/edge
wss.mexc.initMessage={"method":"sub.kline","param":{"symbol":"BTC_USDT","interval":"Min1"}}
wss.mexc.pingMessage={"method": "ping"}
wss.mexc.pingInterval=15
kafka.mexc.output.topic=market-data
kafka.mexc.output.error=mexc-error
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.tbot.cyclop.Cyclop.kafka.serializer.MarketDataSerializer
