#!/bin/bash

# ECR repository host
REPO_HOST="055540832687.dkr.ecr.ap-southeast-2.amazonaws.com"

# Authentication token
AUTH_TOKEN="eyJwYXlsb2FkIjoicmxnbG9hQ3ZRdzA0TTBSb280N21Jb2ZSc29GUS9yMjBucUdQa0hBME5VbVdpTGtBek9TRktqczlpQW1ML1hhUVZsRnhEckNhRWVLR2EyMXpDTVozZG9qZHVPWkhrT0JvVzB2Qm4zOHhJOGszNzVWMWdWOUlNWmFsWlVxb2VoRHlqOHJJU094dEgwclNrWFRqSUQ3ZFNkU0JiMFZZZE9iVGdNQnFsMTBoZnJwbkt6R3hCMGxEaWNrWnRFaWp6ZWJFUlVuTjdFbzFWdzBxWWs4UzBYNmwzbFZsVENzczdkZ0c1djhNQ2piVWk5K09tK1Rqb2pBMjA5dHQzMlNrVXVCNmE1WXJocTFsTEtOWXBkek1jZ2cwMDc4OXU4amtjSEwzM2RmeDc0MGJlNkswTFIvakFSS3FxYkFoUmRzRHk4bFJ3Qk1rWDJKdll5Qm80Q0tEb3gwUU1NSmlDbmNLeWdxQWpUc3E4WEw3TUhHOXlSUHZzZWxFbzhqRE5BSEphK2laa3BnMmxaQVc3WVhrbURKZkdEejdsa2hIVG4ybVZLdHhldHBSU0p6c1czeUhCVmFJNWJQQTMyTGgxSG1qR2wwYlhldTM2L3o0NGZlMEVDNnpyZnFvbjBmSUsxTXdaVE9lY0NxR2dVZVdhOUR5K242SWVuM1NCb0RreTlmSmcxRDdzdG5PbXN1dGt2anpYVEZKNGZzaTN5dXhmdjZoS2haN2J1TU5mZXFkQXZUblBNQnNadjNuTU5XRUtoYWxXNmZOT3hNS3k1c2QwRFZORzlyNSt5NTFMclFObkdlcEQvMFlMMVpoTFFVcWY5UGNGbXJLNTZDRTExMGQyWEp2TnpicG5ZaFFUbXppN2dvbjhZcUViVW5JbDkzS0hWaEU5NHQ3QWpkUmZxZzNkeVIxbldkR2tuYnpyVGQvM0V2UEFrRkhndFFwUkc2S29VZXFOYUp2dnR2S1dSOXRhRDBFR0ZXZ0tXVDNFTDN6S0tUVVdvR2ZtcjVueVdYaWpCeGdoajI3S0RzQjdGWFlUZ2xqRG9oTm1wSTdFcGpXMEJhSVUxOUhtaWZVR2doeHBzcGtUR3dIT0R1c2tIOGRETXdhLyt6Y21PLzQ3YjFjNmJFL3JCOEowQy9acEhYT2pvUjRBZGRuTnhCWUhOTlNtNnBETUlieFhWcFYxbjBXUU1zNHlMNDJmTUY1TGgyaDF5S0tVcW1UajRKMStXaUFzYm11RXpWaFNXNFExSWF5R0k3UWEvcHF3VVFPWm1IQlhEQ3JRRG5XWU45YVN4S25Ta21wcnl0RzFrMHQvZDVieGRKMytJSGdGOFA0YUJQS2ZqUG5HdkhTT2F5VHJrZEhXR0pGamZDcnFkckkwb2FBcTBjaTFnNlJjY0lzUjBqQWttZjhMb0l0RVd6OE5PUT0iLCJkYXRha2V5IjoiQVFFQkFIaEx5ano3UEpFUG1ZYnFINkE2Zi93V056eXo1QkthMzdCbkJQc0F5dUYxS1FBQUFINHdmQVlKS29aSWh2Y05BUWNHb0c4d2JRSUJBREJvQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREl6SUZldHZXZFN6cWd0eXJnSUJFSUE3aWFMVzRzQXZQaFI3cVpwSm5DZ0pGS3NZSzE5ZGkyQzF4S29icVR6dENPOCt1dDhzVjdId2FpRTFNV0xEL1d3bVM4cFJYQXJFcmRpRkV3ST0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE3MTAxMzU0MDB9"

# Check if Docker image argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <docker-image>"
    exit 1
fi

# Docker image passed as argument
DOCKER_IMAGE="$1"

# Login to ECR using authentication token
echo "Logging in to Amazon ECR..."
echo "$AUTH_TOKEN" | docker login --username AWS --password-stdin $REPO_HOST/"$DOCKER_IMAGE"

# Tag the local Docker image with the ECR repository URI
TAG="latest"
docker tag "$DOCKER_IMAGE" $REPO_HOST/"$DOCKER_IMAGE":"$TAG"

# Push the tagged Docker image to the ECR repository
echo "Pushing Docker image to Amazon ECR... : $DOCKER_IMAGE"
docker push $REPO_HOST/"$DOCKER_IMAGE":"$TAG"

# Verify the image has been pushed successfully
if [ $? -eq 0 ]; then
    echo "Docker image successfully pushed to Amazon ECR."
else
    echo "Failed to push Docker image to Amazon ECR."
fi
