spring.data.mongodb.uri=mongodb://root:root@ec2-47-129-30-225.ap-southeast-1.compute.amazonaws.com/2tbot?directConnection=true&tls=false
spring.cloud.stream.bindings.process-in-0.destination=kline-data
spring.cloud.stream.bindings.process-out-0.destination=candle
spring.kafka.bootstrap-servers=localhost:9092
