spring.data.mongodb.uri=mongodb://root:root@ec2-47-129-30-225.ap-southeast-1.compute.amazonaws.com/?directConnection=true&tls=false
spring.data.mongodb.database=2tbot-be
spring.cloud.stream.bindings.process-in-0.destination=kline
spring.cloud.stream.bindings.process-in-0.group=order-placer
spring.cloud.stream.bindings.process-out-0.destination=order-ack
spring.cloud.stream.kafka.bindings.process-in-0.consumer.ack-mode=TIME
spring.kafka.consumer.max-poll-records=300
spring.kafka.listener.concurrency=2
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-placer
spring.cloud.stream.kafka.streams.binder.applicationId=order-placer

mexc.contract.api.baseUrl=https://contract.mexc.com/api/v1/private/
mexc.order.api.baseUrl=https://futures.mexc.com/
bybit.contract.api.baseUrl=https://api.bybit.com/contract/v3/private/
bot.strategy.refreshRate=300000