spring.data.mongodb.uri=mongodb://root:root@ec2-47-129-30-225.ap-southeast-1.compute.amazonaws.com/?directConnection=true&tls=false
spring.data.mongodb.database=2tbot-be
spring.cloud.stream.bindings.process-in-0.destination=kline-data-new
spring.cloud.stream.kafka.bindings.input.consumer.ack-mode=RECORD
spring.cloud.stream.kafka.bindings.input.consumer.configuration.auto.offset.reset=true
spring.cloud.stream.kafka.bindings.input.consumer.startOffset=latest
spring.cloud.stream.bindings.process-out-0.destination=order-ack
spring.kafka.bootstrap-servers=localhost:9092
